# https://github.com/marketplace/actions/clang-format-github-action

name: clang-format Check
on: [ push, pull_request ]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: 'src'
          style: file